Web/Controllers/ShortUrlController.cs
using Domains.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Services.DataServices;
using System.Data.SqlTypes;
using Web.Filters;

namespace Web.Controllers {
    public class ShortUrlController : Controller {
        private readonly ShortUrlDataService _dataService;

        public ShortUrlController(ShortUrlDataService dataService) {
            _dataService = dataService;
        }

        public async Task<IActionResult> Index() {
            var shortUrls = await _dataService.GetAsync();
            return View(shortUrls);
        }

        public async Task<IActionResult> RedirectToUrl(string hash) {
            try {
                var shortUrl = await _dataService.GetByHashAsync(hash);
                await _dataService.IncrementTransitionsCountAsync(shortUrl);
                string url = Uri.EscapeUriString(shortUrl.Url);
                return Redirect(url);
            }
            catch (SqlNullValueException ex) {
                return RedirectToAction(nameof(Error), new { ex.Message });
            }
        }

        public IActionResult Error(string message) {
            return View(model: message);
        }

        public async Task<IActionResult> Delete(int id) {
            await _dataService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Add() {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [UrlIsValidFilter]
        public async Task<IActionResult> Add(AddShortUrlViewModel model) {
            if (ModelState.IsValid) {
                try {
                    await _dataService.AddAsync(model);
                    return RedirectToAction(nameof(Index));
                }
                catch (SqlAlreadyFilledException ex) {
                    ModelState.AddModelError("Url", ex.Message);
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(int id) {
            try {
                var shortUrl = await _dataService.GetAsync(id);
                var updateModel = new UpdateShortUrlViewModel() { Id = shortUrl.Id, Url = shortUrl.Url };
                return View(updateModel);
            }
            catch (SqlNullValueException ex) {
                return RedirectToAction(nameof(Error), new { ex.Message });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [UrlIsValidFilter]
        public async Task<IActionResult> Edit(UpdateShortUrlViewModel model) {
            if (ModelState.IsValid) {
                try {
                    await _dataService.UpdateAsync(model);
                    return RedirectToAction(nameof(Index));
                }
                catch (SqlAlreadyFilledException ex) {
                    ModelState.AddModelError("Url", ex.Message);
                }
            }
            return View(model);
        }
    }
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="ShortUrl" asp-action="Index">Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="ShortUrl" asp-action="Index">Urls List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="ShortUrl" asp-action="Add">Short URL</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Web - Test Task URL Shortener
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/Views/ShortUrl/Add.cshtml
@using Domains.ViewModels﻿
@model AddShortUrlViewModel
@{
    ViewData["Title"] = "Add Short Url";
}

<h1 class="display-4 text-primary text-center">Short Url</h1>
<div class="row d-flex justify-content-center mb-2">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-floating mb-3">
                <input asp-for="Url" class="form-control" autocomplete="@Html.DisplayNameFor(model => model.Url)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.Url)" />
                <label asp-for="Url">@Html.DisplayNameFor(model => model.Url)</label>
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <input type="submit" value="Short" class="w-100 btn btn-lg btn-primary mt-2" />
        </form>
    </div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Web/Views/ShortUrl/Edit.cshtml
@using Domains.ViewModels
@model UpdateShortUrlViewModel
@{
    ViewData["Title"] = "Edit Url";
}
<h1 class="display-4 text-primary text-center">Edit Url</h1>
<div class="row d-flex justify-content-center mb-2">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-floating mb-3">
                <input asp-for="Url" class="form-control" autocomplete="@Html.DisplayNameFor(model => model.Url)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.Url)" />
                <label asp-for="Url">@Html.DisplayNameFor(model => model.Url)</label>
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>

            <input type="submit" value="Save" class="w-100 btn btn-lg btn-primary mt-2" />
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Web/Views/ShortUrl/Index.cshtml
@using Domains.Domains
@model IEnumerable<ShortUrl>
@{
    ViewData["Title"] = "Short Urls List";
}

<div class="text-center">
    @if(Model.Count() == 0){
        <p class="display-3 text-primary font-weight-bold">Database is empty</p>
    }
    else{
        <table class="table table-striped">
            <thead>
                <tr>
                   <th>
                        <b>Long Url</b>
                    </th>
                    <th>
                        <b>Short Url</b>
                    </th>
                    <th>
                        <b>Creating Date</b>
                    </th>
                    <th>
                        <b>Transitions Count</b>
                    </th>
                    <th></th>
            </thead>
            <tbody>
                @foreach (var shortUrl in Model) {
                    <tr>
                        <td>
                            <a href="@shortUrl.Url">
                                @{
                                    string compresedLongUrl = shortUrl.Url.Length > 50 ? shortUrl.Url.Substring(0, 50) + "..." : shortUrl.Url;
                                }

                                @Html.DisplayFor(modelItem => compresedLongUrl)
                            </a>
                        </td>
                        <td>
                            <a href="/@shortUrl.Hash">
                                @{
                                    string shortUrlWithHost = $"{ViewContext.HttpContext.Request.Scheme}://{ViewContext.HttpContext.Request.Host}/{shortUrl.Hash}";
                                }
                                @Html.DisplayFor(modelItem => shortUrlWithHost)
                            </a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => shortUrl.CreatingDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => shortUrl.TransitionsCount)
                        </td>
                        <td>
                            <div class="btn-group">
                                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@shortUrl.Id">Edit</a>
                                <a class="btn btn-primary" asp-action="Delete" asp-route-id="@shortUrl.Id">Delete</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }    
</div>